//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwiddleToe.State {
    
    
    /// The state class
    public class State {
        
        /// The Test class
        public class Test {
            
            private string name;
            
            private int description;
            
            /// Gets or sets the Name
            public virtual string Name {
                get {
                    return this.name;
                }
                set {
                    this.Name = value;
                }
            }
            
            /// Gets or sets the Description
            public virtual int Description {
                get {
                    return this.description;
                }
                set {
                    this.Description = value;
                }
            }
        }
    }
}
